#ifndef __LightGuiderDeviceDialog__
#define __LightGuiderDeviceDialog__

/**
@file
Subclass of DeviceDialog, which is generated by wxFormBuilder.
*/

#include "LightGuiderDeviceDialogBase.h"
#include "lightguider.h"

//// end generated include

/** Implementing DeviceDialog */
class LightGuiderDeviceDialog : public DeviceDialog {
protected:
    // Handlers for DeviceDialog events.
    void on_camera_settings_click(wxCommandEvent& event);
    void on_camera_connect_click(wxCommandEvent& event);
    void on_camera_scan_click(wxCommandEvent& event);

public:
    /** Constructor */
    LightGuiderDeviceDialog(wxWindow* parent);
    //// end generated class members
};

class LightGuiderDeviceDialogFactory {
public:
    static wxDialog* MakeDeviceDialog();
};

#endif  // __LightGuiderDeviceDialog__
