#ifndef __LightGuiderServerDialog__
#define __LightGuiderServerDialog__

/**
@file
Subclass of ServerDialog, which is generated by wxFormBuilder.
*/

#include "lightguider.h"
#include "server_dialog_base.h"

//// end generated include

/** Implementing ServerDialog */
class LightGuiderServerDialog : public ServerDialog {
protected:
    // Handlers for ServerDialog events.
    void start_server(wxCommandEvent& event);
    void stop_server(wxCommandEvent& event);
    void config_server(wxCommandEvent& event);
    void open_server(wxCommandEvent& event);
    void start_webserver(wxCommandEvent& event);
    void stop_webserver(wxCommandEvent& event);

public:
    /** Constructor */
    LightGuiderServerDialog(wxWindow* parent);
    ~LightGuiderServerDialog();
    //// end generated class members
};

class ServerAssistantFactory {
public:
    static wxDialog* MakeServerAssistant();
};

#endif  // __LightGuiderServerDialog__
