#ifndef __SodiumDeviceDialog__
#define __SodiumDeviceDialog__

/**
@file
Subclass of DeviceDialog, which is generated by wxFormBuilder.
*/

#include "SodiumDeviceDialogBase.hpp"
#include "sodium.hpp"

//// end generated include

/** Implementing DeviceDialog */
class SodiumDeviceDialog : public DeviceDialog {
protected:
    // Handlers for DeviceDialog events.
    void on_camera_settings_click(wxCommandEvent& event);
    void on_camera_connect_click(wxCommandEvent& event);
    void on_camera_scan_click(wxCommandEvent& event);

public:
    /** Constructor */
    SodiumDeviceDialog(wxWindow* parent);
    //// end generated class members
};

class SodiumDeviceDialogFactory {
public:
    static wxDialog* MakeDeviceDialog();
};

#endif  // __SodiumDeviceDialog__
