#ifndef __LightGuiderSolverAssistant__
#define __LightGuiderSolverAssistant__

/**
@file
Subclass of SolverAssistant, which is generated by wxFormBuilder.
*/

#include "lightguider.h"
#include "solver_dialog_base.h"
//// end generated include

/** Implementing SolverAssistant */
class LightGuiderSolverAssistant : public SolverAssistant
{
	protected:
		// Handlers for SolverAssistant events.
		void on_solver_changed( wxFileDirPickerEvent& event );
		void on_solver_search( wxCommandEvent& event );
		void refresh_solver_ra( wxMouseEvent& event );
		void on_ra_enter( wxCommandEvent& event );
		void refresh_solver_dec( wxMouseEvent& event );
		void on_dec_enter( wxCommandEvent& event );
		void on_fov_enter( wxCommandEvent& event );
		void check_template_downloaded( wxCommandEvent& event );
		void on_refresh_template( wxCommandEvent& event );
		void on_download_template( wxCommandEvent& event );
		void on_open_template_folder( wxCommandEvent& event );
		void on_start_solver( wxCommandEvent& event );
		void on_stop_solver( wxCommandEvent& event );
		void on_copy_solver( wxCommandEvent& event );
		void on_exit_solver( wxCommandEvent& event );
		void on_help_solver( wxCommandEvent& event );
		void on_copy_solver_result_ra( wxMouseEvent& event );
		void on_copy_solver_result_dec( wxMouseEvent& event );
		void on_copy_solver_result_rotation( wxMouseEvent& event );
		void on_copy_solver_result_fovx( wxMouseEvent& event );
		void on_copy_solver_result_fovy( wxMouseEvent& event );
	public:
		/** Constructor */
		LightGuiderSolverAssistant( wxWindow* parent );
	//// end generated class members

};

class SolverAssistantFactory
{
public:
    static wxDialog *MakeSolverAssistant();
};

#endif // __LightGuiderSolverAssistant__
